### ISSUE TITLE
Add a element target to display scroll progress for this element

### ISSUE THREAD

**Issue by jmsche** [stimulus-components/stimulus-scroll-progress#2]
Hi,

It would be nice to have a element target option, which would allow to watch the specific element instead of the entire body?

Would be useful for e.g. blog articles :) 

Thanks!

**Comment by guillaumebriday** [comment]
Hum I think it's really specific and most of the time, the scroll progress bar is relative to  the whole page.

You should probably override the scroll function here 👍 

But if you open a PR with what you have in mind I'll give it a shot! 👍
