### ISSUE TITLE
Remove lodash/throttle dependency

### ISSUE THREAD

**Issue by florentdestremau** [stimulus-components/stimulus-scroll-progress#3]
When trying to use this component in a Symfony project using the Assets Mapper component (which relies on import maps), this stimulus component errors because of the lodash/throttle import.

`+esm:7 Uncaught SyntaxError: The requested module '/npm/lodash/+esm' does not provide an export named 'throttle' (at +esm:7:72)`

![Screenshot from 2023-12-19 16-30-25](https://github.com/stimulus-components/stimulus-scroll-progress/assets/2852204/9276942f-8391-4752-a657-82cd4508e94d)

I feel like such a dependency should not be necessary for a small component. An inline throttle could be used instead.

**Comment by guillaumebriday** [comment]
Hi! Thanks for the suggestion you're are absolutely right, I opened a PR to fix that, can you review it? https://github.com/stimulus-components/stimulus-scroll-progress/pull/4

So I could release 4.2.0 after that

**Comment by florentdestremau** [comment]
Thanks for your contribution :) Have a nice end of the year
